SOURCES += \
	../Blackfin/Src/TdmMng/BoolALawToRtpPayload.cpp \
	../Blackfin/Src/TdmMng/DataPacket.cpp 		\
	../Blackfin/Src/TdmMng/RtpToTdmBuff.cpp 	\
	../Blackfin/Src/TdmMng/RtpToTdmBufferStat.cpp 	\
	../Blackfin/Src/TdmMng/SendToRtp.cpp 		\
	../Blackfin/Src/TdmMng/TdmBlockWrappers.cpp 	\
	../Blackfin/Src/TdmMng/TdmAsyncEvent.cpp 	\
	../Blackfin/Src/TdmMng/TdmChannel.cpp 		\
	../Blackfin/Src/TdmMng/TdmChannelSender.cpp 	\
	../Src/TdmMng/TdmChannelSender_i.cpp 		\
	../Blackfin/Src/TdmMng/TdmHAL.cpp 		\
	../Blackfin/Src/TdmMng/TdmManager.cpp 		\
	../Blackfin/Src/TdmMng/TdmStream.cpp 		\
	../Blackfin/Src/TdmMng/TdmStreamStat.cpp 	\
	../Blackfin/Src/TdmMng/TdmToTdmBuff.cpp 	\
	../Blackfin/Src/TdmMng/TestRtpToTdm.cpp 	\
	../Blackfin/Src/TdmMng/TdmSyncTxCopy.cpp \
	../Blackfin/Src/TdmMng/TdmEchoSuppress.cpp \
